title: Nguyen Phuc Ngoc Thanh
description: This is my blog hosted on GitHub Pages.
theme: minima
author: Nguyen Phuc Ngoc Thanh

minima:
  social_links:
    - title: Email
      icon: envelope
      url: mailto:ngocthanhxs2@gmail.com
    - title: Facebook
      icon: facebook
      url: https://www.facebook.com/NguyenPhucNgocThanh03.01.99/
    - title: LinkedIn
      icon: linkedin
      url: https://www.linkedin.com/in/thanhnpn/
    - title: GitHub
      icon: github
      url: https://github.com/npngocthanh99
